### ISSUE TITLE
Nice work! :)

### ISSUE THREAD

**Issue by danielweck** [thephilgray/custom-readaloud-plugin#14]
Reminds me of SMIL Timesheets:

http://wam.inrialpes.fr/timesheets/

https://github.com/timesheets/timesheets.js

Cool project(s), thanks!

**Comment by danielweck** [comment]
You may close this non-issue ;)

**Comment by thephilgray** [comment]
Hi @danielweck, 

Thanks for taking the time to review my projects and provide feedback. I'm still new to the EPUB field (< 1yr), and it's good to hear from the community! I especially appreciate the links to other projects, as I hadn't come across these.

Thanks!
